### PR TITLE
[WIP] Add Android compatibility

### PR DESCRIPTION
**Pull request by Jberlinsky**
Addresses https://github.com/doefler/react-native-social-share/issues/30 & https://github.com/doefler/react-native-social-share/issues/26

This pull request adds Android compatibility for sharing via Twitter. *Note that this only provides the `tweet` method at present, and Facebook is not supported yet.*

Sharing via Twitter will check for the presence of the Twitter application, and will use its provided intent if available. Otherwise, it will open a web browser to compose the tweet.

TODO:

- [ ] Get https://github.com/doefler/react-native-social-share/pull/34 merged in
- [x] Support Facebook sharing
- [x] Support the various options that iOS supports

### CODE REVIEW

**Comment by Jberlinsky** [comment]
Due to [known issues](http://stackoverflow.com/questions/23541823/how-to-share-text-and-image-on-facebook-using-intent) with shelling out to the Facebook application-provided Intents, Android can't handle all of the arguments that iOS can. I'll update the README to reflect accordingly.

**Comment by Jberlinsky** [comment]
This PR is ready to merge once #34 is merged in (in order to develop on it, I had to cherry-pick the commits from that PR onto this branch).

**Comment by doefler** [comment]
I merged both PR @Jberlinsky 
Great work 😄 
I made a small correction in the code sample in the readme.md

**Comment by doefler** [comment]
@Jberlinsky let me know if you need other changes for it to work.
As I understand it was difficult since #34 wasn't merged.
After that I will do a version update to NPM

**Comment by Jberlinsky** [comment]
@doefler That should just about do it, thanks!

**Comment by doefler** [comment]
@Jberlinsky cool, I will do a NPM version update then 👍

**Pull request merged**
